export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESSFUL ="LOGIN_SUCCESSFUL";
export const LOGIN_FAIL ="LOGIN_FAIL";
export const LOGOUT ="LOGOUT";